apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: apr1-updated-docs-3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apr1-updated-docs-3
  name: apr1-updated-docs-3
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
